name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    container:
      image: cypress/browsers:latest
      options: --user 1001
    steps:
    - uses: actions/checkout@v4
    - uses: cypress-io/github-action@v6
      with:
        browser: chrome